name: Build Custom FFmpegKit iOS

on:
  push:
    tags:
      - 'v*'

jobs:
  build-custom-ios:
    name: iOS Build on macOS Sonoma
    runs-on: macos-14
    strategy:
      matrix:
        xcode: [ '15.4' ]
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: brew install autoconf automake libtool pkg-config curl git cmake nasm

      - name: Set up Xcode
        run: echo "export DEVELOPER_DIR=/Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer" > ~/.xcode.for.ffmpeg.kit.sh

      - name: Build ffmpeg-kit ios
        run: ./ios.sh --xcframework --enable-ios-avfoundation --enable-ios-videotoolbox --enable-ios-audiotoolbox --enable-ios-libiconv --enable-ios-zlib

      - name: Create prebuilt folder
        run: mkdir -p prebuilt

      - name: Verify framework presence
        run: ls -la ffmpegkit.xcframework

      - name: Zip built xcframework
        run: zip -r prebuilt/ffmpeg-kit-full-${{ github.ref_name }}-ios-xcframework.zip ffmpegkit.xcframework

      - name: Upload XCFramework to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: prebuilt/ffmpeg-kit-full-${{ github.ref_name }}-ios-xcframework.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
