name: Build Custom FFmpegKit iOS & tvOS

on:
  push:
    tags:
      - 'v*'

jobs:
  build-ios:
    name: iOS Build on macOS Sonoma
    runs-on: macos-14
    strategy:
      matrix:
        xcode: ['15.4']
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: brew install autoconf automake libtool pkg-config curl git cmake nasm

      - name: Set up Xcode
        run: echo "export DEVELOPER_DIR=/Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer" > ~/.xcode.for.ffmpeg.kit.sh

      - name: Build ffmpeg-kit for iOS
        run: ./ios.sh --xcframework --enable-ios-avfoundation --enable-ios-videotoolbox --enable-ios-audiotoolbox --enable-ios-libiconv --enable-ios-zlib

      - name: Create prebuilt folder
        run: mkdir -p prebuilt

      - name: Find generated iOS XCFramework
        id: find_ios
        run: |
          IOS_FRAMEWORK=$(find . -name "*.xcframework" -type d | head -n 1)
          echo "IOS_FRAMEWORK=$IOS_FRAMEWORK" >> $GITHUB_ENV

      - name: Zip iOS XCFramework
        run: zip -r prebuilt/ffmpeg-kit-full-${{ github.ref_name }}-ios-xcframework.zip "$IOS_FRAMEWORK"

      - name: Upload iOS XCFramework to Release
        uses: softprops/action-gh-release@v1
        with:
          files: prebuilt/ffmpeg-kit-full-${{ github.ref_name }}-ios-xcframework.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-tvos:
    name: tvOS Build on macOS Sonoma
    runs-on: macos-14
    strategy:
      matrix:
        xcode: ['15.4']
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: brew install autoconf automake libtool pkg-config curl git cmake nasm

      - name: Set up Xcode
        run: echo "export DEVELOPER_DIR=/Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer" > ~/.xcode.for.ffmpeg.kit.sh

      - name: Build ffmpeg-kit for tvOS
        run: ./tvos.sh --xcframework --enable-tvos-avfoundation --enable-tvos-videotoolbox --enable-tvos-audiotoolbox --enable-tvos-libiconv --enable-tvos-zlib

      - name: Create prebuilt folder
        run: mkdir -p prebuilt

      - name: Find generated tvOS XCFramework
        id: find_tvos
        run: |
          TVOS_FRAMEWORK=$(find . -name "*.xcframework" -type d | head -n 1)
          echo "TVOS_FRAMEWORK=$TVOS_FRAMEWORK" >> $GITHUB_ENV

      - name: Zip tvOS XCFramework
        run: zip -r prebuilt/ffmpeg-kit-full-${{ github.ref_name }}-tvos-xcframework.zip "$TVOS_FRAMEWORK"

      - name: Upload tvOS XCFramework to Release
        uses: softprops/action-gh-release@v1
        with:
          files: prebuilt/ffmpeg-kit-full-${{ github.ref_name }}-tvos-xcframework.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
